// Generated by tools/scripts/png_cursor_to_c.py. Do not edit.
#ifndef MARU_CURSOR_ASSETS_H_INCLUDED
#define MARU_CURSOR_ASSETS_H_INCLUDED

#include <stdint.h>

#include "maru/maru.h"

typedef struct MARU_CursorBitmapAsset {
  uint32_t width;
  uint32_t height;
  uint32_t stride_bytes;
  int32_t hot_x;
  int32_t hot_y;
  const uint32_t *pixels_argb;
} MARU_CursorBitmapAsset;

extern const MARU_CursorBitmapAsset g_maru_cursor_bitmap_assets[MARU_CURSOR_SHAPE_NWSE_RESIZE + 1u];

#endif  // MARU_CURSOR_ASSETS_H_INCLUDED
