#ifndef MARU_CONFIG_H_INCLUDED
#define MARU_CONFIG_H_INCLUDED

// Library version
#define MARU_VERSION_MAJOR 0
#define MARU_VERSION_MINOR 1
#define MARU_VERSION_PATCH 0

// Backends
#define MARU_ENABLE_BACKEND_WAYLAND
#define MARU_ENABLE_BACKEND_X11
/* #undef MARU_ENABLE_BACKEND_COCOA */
/* #undef MARU_ENABLE_BACKEND_WINDOWS */

// Diagnostics
#define MARU_ENABLE_DIAGNOSTICS
#define MARU_VALIDATE_API_CALLS
/* #undef MARU_ENABLE_INTERNAL_CHECKS */
/* #undef MARU_ENABLE_FAULT_INJECTION */

#endif  // MARU_CONFIG_H_INCLUDED
